name: flutter_notify
description: Telegram bot for Flutter release notifications.
version: 0.1.0
repository: https://github.com/minhqdao/flutter_notify

environment:
  sdk: ^3.10.4

dependencies:
  deep_pick: ^1.1.0
  drift: ^2.30.0
  pub_semver: ^2.2.0
  shelf: ^1.4.2
  shelf_router: ^1.1.4
  sqlite3: ^2.9.4

dev_dependencies:
  build_runner: ^2.10.4
  drift_dev: ^2.30.0
  lint: ^2.8.0
